In [1]:
import tensorflow as tf
print(tf.__version__)

2.0.0-rc0


In [2]:
print(issubclass(tf.keras.Model,tf.Module))
print(issubclass(tf.keras.layers.Layer,tf.Module))
print(issubclass(tf.keras.Model,tf.keras.layers.Layer))

True
True
True


$ y = x \cdot w + b $  

假设 $ x \in R^{(2,2)} , w \in R^{(2,2)} ,b \in R^{(4)} $ 返回 $ y \in R^{(2,4)} $

下面我们实现上面的线性层：

In [3]:
import tensorflow as tf
print(tf.__version__)

# 定义全连接层
class Linear(tf.keras.layers.Layer):
    
    def __init__(self, units=32, input_dim=32):
        super(Linear, self).__init__()
        w_init = tf.random_normal_initializer()
        self.w = tf.Variable(initial_value=w_init(shape=(input_dim,units), dtype='float32'), trainable=True)
        b_init = tf.zeros_initializer()
        self.b = tf.Variable(initial_value = b_init(shape=(units,), dtype='float32'), trainable=True)
    def call(self, inputs):
        return tf.matmul(inputs, self.w) + self.b
    
x =  tf.ones((2,2))

linear_layer = Linear(4, 2)
y = linear_layer(x)
print(y)

2.0.0-rc0
tf.Tensor(
[[-0.04971659 -0.0679535   0.05104972 -0.08182988]
 [-0.04971659 -0.0679535   0.05104972 -0.08182988]], shape=(2, 4), dtype=float32)


In [4]:
linear_layer.trainable_variables

[<tf.Variable 'Variable:0' shape=(2, 4) dtype=float32, numpy=
 array([[-0.0034666 , -0.03838873,  0.04819738, -0.0603306 ],
        [-0.04624998, -0.02956477,  0.00285233, -0.02149929]],
       dtype=float32)>,
 <tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>]

In [5]:
linear_layer.w

<tf.Variable 'Variable:0' shape=(2, 4) dtype=float32, numpy=
array([[-0.0034666 , -0.03838873,  0.04819738, -0.0603306 ],
       [-0.04624998, -0.02956477,  0.00285233, -0.02149929]],
      dtype=float32)>

In [6]:
linear_layer.b

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>