# Keras 版本模型保存与加载

## 保存模型与加载模型

In [2]:
import numpy as np
import tensorflow as tf

x_train = np.random.random((1000, 32))
y_train = np.random.randint(10,size=(1000,))
x_val = np.random.random((200,32))
y_val = np.random.randint(10,size=(200,))
x_test = np.random.random((200,32))
y_test = np.random.randint(10,size=(200,))

In [3]:
def get_uncompiled_model():
    inputs = tf.keras.Input(shape=(32,), name='digits')
    x = tf.keras.layers.Dense(64, activation='relu', name='dense_1')(inputs)
    x = tf.keras.layers.Dense(64, activation='relu', name='dense_2')(x)
    outputs = tf.keras.layers.Dense(10, name='predictions')(x)
    model = tf.keras.Model(inputs=inputs,outputs=outputs)
    return model

def get_compiled_model():
    model = get_uncompiled_model()
    model.compile(optimizer=tf.keras.optimizers.RMSprop(learning_rate=1e-3),
                 loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
                 metrics=['sparse_categorical_accuracy'])
    return model

In [4]:
model = get_compiled_model()
model.fit(x_train, y_train, batch_size=32, epochs=5,validation_data=(x_val,y_val))

Train on 1000 samples, validate on 200 samples
Epoch 1/5
1000/1000 [==============================] - 1s 627us/sample - loss: 2.3216 - sparse_categorical_accuracy: 0.1080 - val_loss: 2.3229 - val_sparse_categorical_accuracy: 0.0950
Epoch 2/5
1000/1000 [==============================] - 0s 68us/sample - loss: 2.2932 - sparse_categorical_accuracy: 0.1120 - val_loss: 2.3215 - val_sparse_categorical_accuracy: 0.1300
Epoch 3/5
1000/1000 [==============================] - 0s 81us/sample - loss: 2.2802 - sparse_categorical_accuracy: 0.1260 - val_loss: 2.3218 - val_sparse_categorical_accuracy: 0.1100
Epoch 4/5
1000/1000 [==============================] - 0s 66us/sample - loss: 2.2718 - sparse_categorical_accuracy: 0.1460 - val_loss: 2.3127 - val_sparse_categorical_accuracy: 0.1050
Epoch 5/5
1000/1000 [==============================] - 0s 65us/sample - loss: 2.2601 - sparse_categorical_accuracy: 0.1540 - val_loss: 2.3175 - val_sparse_categorical_accuracy: 0.1200


In [5]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
digits (InputLayer)          [(None, 32)]              0         
_________________________________________________________________
dense_1 (Dense)              (None, 64)                2112      
_________________________________________________________________
dense_2 (Dense)              (None, 64)                4160      
_________________________________________________________________
predictions (Dense)          (None, 10)                650       
Total params: 6,922
Trainable params: 6,922
Non-trainable params: 0
_________________________________________________________________


## 方法一

In [7]:
model.save_weights('adasd.h5')
model.load_weights('adasd.h5')
model.predict(x_test)

array([[ 0.3473292 ,  0.3046521 , -0.23478134, ...,  0.13323289,
        -0.34092686, -0.01059906],
       [ 0.16159756,  0.01305328,  0.08097283, ..., -0.01362841,
         0.1453599 , -0.02191441],
       [ 0.33781755,  0.25096965, -0.19106542, ...,  0.3070628 ,
        -0.1019905 , -0.07908364],
       ...,
       [ 0.04942468,  0.14382668, -0.2340227 , ...,  0.11744707,
        -0.12604512,  0.16752988],
       [ 0.01535964,  0.06849495, -0.08979256, ..., -0.20046854,
         0.03855814,  0.08254822],
       [ 0.08698934,  0.11025517, -0.0973656 , ..., -0.03306213,
         0.25290254,  0.3312022 ]], dtype=float32)

In [8]:
model.save_weights('./checkpoints/mannul_checkpoint')
model.load_weights('./checkpoints/mannul_checkpoint')
model.predict(x_test)

array([[ 0.3473292 ,  0.3046521 , -0.23478134, ...,  0.13323289,
        -0.34092686, -0.01059906],
       [ 0.16159756,  0.01305328,  0.08097283, ..., -0.01362841,
         0.1453599 , -0.02191441],
       [ 0.33781755,  0.25096965, -0.19106542, ...,  0.3070628 ,
        -0.1019905 , -0.07908364],
       ...,
       [ 0.04942468,  0.14382668, -0.2340227 , ...,  0.11744707,
        -0.12604512,  0.16752988],
       [ 0.01535964,  0.06849495, -0.08979256, ..., -0.20046854,
         0.03855814,  0.08254822],
       [ 0.08698934,  0.11025517, -0.0973656 , ..., -0.03306213,
         0.25290254,  0.3312022 ]], dtype=float32)

## 方法二

In [9]:
# Export the model to a SavedModel
model.save('keras_model_tf_version', save_format='tf')

#Recreate the exact same model
new_model = tf.keras.models.load_model('keras_model_tf_version')
new_model.predict(x_test)

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
INFO:tensorflow:Assets written to: keras_model_tf_version\assets


array([[ 0.3473292 ,  0.3046521 , -0.23478134, ...,  0.13323289,
        -0.34092686, -0.01059906],
       [ 0.16159756,  0.01305328,  0.08097283, ..., -0.01362841,
         0.1453599 , -0.02191441],
       [ 0.33781755,  0.25096965, -0.19106542, ...,  0.3070628 ,
        -0.1019905 , -0.07908364],
       ...,
       [ 0.04942468,  0.14382668, -0.2340227 , ...,  0.11744707,
        -0.12604512,  0.16752988],
       [ 0.01535964,  0.06849495, -0.08979256, ..., -0.20046854,
         0.03855814,  0.08254822],
       [ 0.08698934,  0.11025517, -0.0973656 , ..., -0.03306213,
         0.25290254,  0.3312022 ]], dtype=float32)

## 方法三

In [10]:
model.save('keras_model_hdf5_version.h5')

new_model = tf.keras.models.load_model('keras_model_hdf5_version.h5')
new_model.predict(x_test)

array([[ 0.3473292 ,  0.3046521 , -0.23478134, ...,  0.13323289,
        -0.34092686, -0.01059906],
       [ 0.16159756,  0.01305328,  0.08097283, ..., -0.01362841,
         0.1453599 , -0.02191441],
       [ 0.33781755,  0.25096965, -0.19106542, ...,  0.3070628 ,
        -0.1019905 , -0.07908364],
       ...,
       [ 0.04942468,  0.14382668, -0.2340227 , ...,  0.11744707,
        -0.12604512,  0.16752988],
       [ 0.01535964,  0.06849495, -0.08979256, ..., -0.20046854,
         0.03855814,  0.08254822],
       [ 0.08698934,  0.11025517, -0.0973656 , ..., -0.03306213,
         0.25290254,  0.3312022 ]], dtype=float32)

## 方法四 

In [12]:
tf.saved_model.save(model, 'tf_saved_model_version')
restored_saved_model = tf.saved_model.load('tf_saved_model_version')
f = restored_saved_model.signatures["serving_default"]

INFO:tensorflow:Assets written to: tf_saved_model_version\assets


In [14]:
f(digits = tf.constant(x_test.tolist()))

{'predictions': <tf.Tensor: id=6595, shape=(200, 10), dtype=float32, numpy=
 array([[ 0.3473292 ,  0.3046521 , -0.23478134, ...,  0.13323289,
         -0.34092686, -0.01059906],
        [ 0.16159756,  0.01305328,  0.08097283, ..., -0.01362841,
          0.1453599 , -0.02191441],
        [ 0.33781755,  0.25096965, -0.19106542, ...,  0.3070628 ,
         -0.1019905 , -0.07908364],
        ...,
        [ 0.04942468,  0.14382668, -0.2340227 , ...,  0.11744707,
         -0.12604512,  0.16752988],
        [ 0.01535964,  0.06849495, -0.08979256, ..., -0.20046854,
          0.03855814,  0.08254822],
        [ 0.08698934,  0.11025517, -0.0973656 , ..., -0.03306213,
          0.25290254,  0.3312022 ]], dtype=float32)>}

In [15]:
!saved_model_cli show --dir tf_saved_model_version --all


MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['__saved_model_init_op']:
  The given SavedModel SignatureDef contains the following input(s):
  The given SavedModel SignatureDef contains the following output(s):
    outputs['__saved_model_init_op'] tensor_info:
        dtype: DT_INVALID
        shape: unknown_rank
        name: NoOp
  Method name is: 

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['digits'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 32)
        name: serving_default_digits:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['predictions'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 10)
        name: StatefulPartitionedCall:0
  Method name is: tensorflow/serving/predict


2020-07-02 15:00:05.745386: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll


# 自定义版本模型保存与加载

In [32]:
import tensorflow as tf

In [33]:
class MyModel(tf.keras.Model):
    
    def __init__(self, num_classes=10):
        super(MyModel, self).__init__(name='my_model')
        self.num_classes = num_classes
        #自定义需要的层
        self.dense_1 = tf.keras.layers.Dense(32, activation='relu')
        self.dense_2 = tf.keras.layers.Dense(num_classes)
    
    @tf.function(input_signature=[tf.TensorSpec([None,32], tf.float32, name='digits')])
    def call(self, inputs):
        # 定义前向传播
        # 使用__init__定义的层
        x = self.dense_1(inputs)
        return self.dense_2(x)

In [36]:
import numpy as np

x_train = np.random.random((1000,32))
y_train = np.random.random((1000,10))
x_val = np.random.random((200,32))
y_val = np.random.random((200,10))
x_test = np.random.random((200, 32))
y_test = np.random.random((200, 10))

# 优化器
optimizer = tf.keras.optimizers.SGD(learning_rate=1e-3)
# 损失函数
loss_fn = tf.keras.losses.CategoricalCrossentropy(from_logits=True)

# 准备metrics函数
train_acc_metric = tf.keras.metrics.CategoricalAccuracy()
val_acc_metric = tf.keras.metrics.CategoricalAccuracy()

# 准备训练数据集
batch_size = 64
train_dataset = tf.data.Dataset.from_tensor_slices((x_train,y_train))
train_dataset = train_dataset.shuffle(buffer_size=1024).batch(batch_size)

# 准备测试数据集
val_dataset = tf.data.Dataset.from_tensor_slices((x_val,y_val))
val_dataset = val_dataset.batch(64)


In [39]:
model = MyModel(num_classes = 10)
epochs = 3
for epoch in range(epochs):
    print('Start of epoch %d' % (epoch,))
    
    #遍历数据集的batch_size
    for step, (x_batch_train,y_batch_train) in enumerate(train_dataset):
        with tf.GradientTape() as tape:
            logits = model(x_batch_train)
            loss_value = loss_fn(y_batch_train, logits)
        grads = tape.gradient(loss_value,model.trainable_weights)
        optimizer.apply_gradients(zip(grads,model.trainable_weights))
        
        # 更新训练集metrics
        train_acc_metric(y_batch_train,logits)
        # 每200 batches 打印一次
        if step % 200 == 0:
            print('Training loss (for on batch) at step %s: %s' % (step,float(loss_value)))
            print('Seen so far: %s samples' % ((step + 1) * 64))
        
    # 每200 batches 打印一次
    train_acc = train_acc_metric.result()
    print('Training acc over epoch : %s' % (float(train_acc),))
    # 在每个epoch结束时重置训练指标
    train_acc_metric.reset_states()
        
    # 在每个epoch结束时运行一个验证集
    for x_batch_val, y_batch_val in val_dataset:
        val_logits = model(x_batch_val)
        # 更新验证集metrics
        val_acc_metric(y_batch_val, val_logits)
    val_acc = val_acc_metric.result()
    val_acc_metric.reset_states()
    print('Validation acc: %s' % (float(val_acc),))
        

Start of epoch 0

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

Training loss (for on batch) at step 0: 11.79886531829834
Seen so far: 64 samples
Training acc over epoch : 0.10599999874830246
Validation acc: 0.10499999672174454
Start of epoch 1
Training loss (for on batch) at step 0: 11.923458099365234
Seen so far: 64 samples
Training acc over epoch : 0.10400000214576721
Validation acc: 0.0949999988079071
Start of epoch 2
Training loss (for on batch) at step 0: 11.96838665008545
Seen so far: 64 samples
Training acc over epoch : 0.10000000149011612
V

## 模型保存方法一

In [40]:
model.save_weights("adasd.h5")
model.load_weights("adasd.h5")
model.predict(x_test)

array([[ 0.4654854 , -0.01458457,  0.15748456, ...,  0.3054785 ,
         0.57802564,  0.38118216],
       [ 0.03840728, -0.19577438,  0.10128754, ...,  0.09494125,
         0.6286599 ,  0.19895615],
       [-0.07822809,  0.39466432,  0.18232784, ...,  0.5844623 ,
         0.3728618 ,  0.7531386 ],
       ...,
       [ 0.8180418 , -0.5025957 , -0.32610843, ...,  0.2350072 ,
         0.91166764,  0.7778447 ],
       [ 0.36247116, -0.3068242 , -0.13966909, ...,  0.192061  ,
         0.50103104,  0.1897213 ],
       [ 0.03541934, -0.07327286, -0.28988874, ...,  0.25282496,
         0.24358226,  0.28250873]], dtype=float32)

In [41]:
model.save_weights('./checkpoints/mannul_checkpoint')
model.load_weights('./checkpoints/mannul_checkpoint')
model.predict(x_test)

array([[ 0.4654854 , -0.01458457,  0.15748456, ...,  0.3054785 ,
         0.57802564,  0.38118216],
       [ 0.03840728, -0.19577438,  0.10128754, ...,  0.09494125,
         0.6286599 ,  0.19895615],
       [-0.07822809,  0.39466432,  0.18232784, ...,  0.5844623 ,
         0.3728618 ,  0.7531386 ],
       ...,
       [ 0.8180418 , -0.5025957 , -0.32610843, ...,  0.2350072 ,
         0.91166764,  0.7778447 ],
       [ 0.36247116, -0.3068242 , -0.13966909, ...,  0.192061  ,
         0.50103104,  0.1897213 ],
       [ 0.03541934, -0.07327286, -0.28988874, ...,  0.25282496,
         0.24358226,  0.28250873]], dtype=float32)

## 模型保存方法二

In [46]:
# model.save('my_saved_model.h5')
# new_model = tf.keras.models.load_model('my_saved_model')
# new_model.predict(x_test)

array([[ 0.26871058,  0.13238555, -0.02399828, ...,  0.09735883,
         0.24049371, -0.11521427],
       [ 0.04897687,  0.12739743,  0.01778143, ...,  0.23483427,
        -0.07434058,  0.07764767],
       [-0.18919535, -0.08100177,  0.12509204, ...,  0.02420731,
         0.16034783, -0.03157626],
       ...,
       [ 0.06580651,  0.14493288, -0.0389459 , ...,  0.03956239,
         0.22903194,  0.08431342],
       [ 0.17668797,  0.17996134, -0.12930757, ...,  0.09321087,
         0.00757388, -0.03637813],
       [-0.09938693, -0.13643418, -0.13194056, ..., -0.0158865 ,
        -0.2620629 ,  0.1127703 ]], dtype=float32)

## 模型保存方法三

In [47]:
model.save('path_to_my_model',save_format='tf')

INFO:tensorflow:Assets written to: path_to_my_model\assets


In [48]:
new_model = tf.keras.models.load_model('path_to_my_model')

In [49]:
new_model.predict(x_test)

array([[ 0.4654854 , -0.01458457,  0.15748456, ...,  0.3054785 ,
         0.57802564,  0.38118216],
       [ 0.03840728, -0.19577438,  0.10128754, ...,  0.09494125,
         0.6286599 ,  0.19895615],
       [-0.07822809,  0.39466432,  0.18232784, ...,  0.5844623 ,
         0.3728618 ,  0.7531386 ],
       ...,
       [ 0.8180418 , -0.5025957 , -0.32610843, ...,  0.2350072 ,
         0.91166764,  0.7778447 ],
       [ 0.36247116, -0.3068242 , -0.13966909, ...,  0.192061  ,
         0.50103104,  0.1897213 ],
       [ 0.03541934, -0.07327286, -0.28988874, ...,  0.25282496,
         0.24358226,  0.28250873]], dtype=float32)

## 模型保存方法四

In [52]:
tf.saved_model.save(model,'my_saved_model')
restored_saved_model = tf.saved_model.load('my_saved_model')
f = restored_saved_model.signatures["serving_default"]

INFO:tensorflow:Assets written to: my_saved_model\assets


In [53]:
f(digits = tf.constant(x_test.tolist()))

{'output_1': <tf.Tensor: id=31416, shape=(200, 10), dtype=float32, numpy=
 array([[ 0.4654854 , -0.01458457,  0.15748456, ...,  0.3054785 ,
          0.57802564,  0.38118216],
        [ 0.03840728, -0.19577438,  0.10128754, ...,  0.09494125,
          0.6286599 ,  0.19895615],
        [-0.07822809,  0.39466432,  0.18232784, ...,  0.5844623 ,
          0.3728618 ,  0.7531386 ],
        ...,
        [ 0.8180418 , -0.5025957 , -0.32610843, ...,  0.2350072 ,
          0.91166764,  0.7778447 ],
        [ 0.36247116, -0.3068242 , -0.13966909, ...,  0.192061  ,
          0.50103104,  0.1897213 ],
        [ 0.03541934, -0.07327286, -0.28988874, ...,  0.25282496,
          0.24358226,  0.28250873]], dtype=float32)>}

In [54]:
!saved_model_cli show --dir my_saved_model --all

2020-07-02 17:12:23.111325: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll



MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['__saved_model_init_op']:
  The given SavedModel SignatureDef contains the following input(s):
  The given SavedModel SignatureDef contains the following output(s):
    outputs['__saved_model_init_op'] tensor_info:
        dtype: DT_INVALID
        shape: unknown_rank
        name: NoOp
  Method name is: 

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['digits'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 32)
        name: serving_default_digits:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['output_1'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 10)
        name: StatefulPartitionedCall:0
  Method name is: tensorflow/serving/predict


In [60]:
a = x_test.tolist()[0]

In [61]:
len(a)

32

In [62]:
aa = list(map(lambda x : int(x),a))

In [63]:
aa

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [65]:
# f(digits = tf.constant([aa]))