In [2]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
print(tf.__version__)
print(np.__version__)

2.2.0
1.18.4


In [7]:
ds = tf.data.Dataset.from_tensor_slices([1,2,3,4])
print(type(ds))
for line in ds:
    print(line)

<class 'tensorflow.python.data.ops.dataset_ops.TensorSliceDataset'>
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


In [8]:
ds = tf.data.Dataset.from_tensors([1,2,3,4])
print(type(ds))
for line in ds:
    print(line)

<class 'tensorflow.python.data.ops.dataset_ops.TensorDataset'>
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [5]:
t = tf.constant([[1,2],[3,4]])
for line in ds:
    print(line)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [6]:
t = tf.constant([[1,2],[3,4]])
ds = tf.data.Dataset.from_tensors({"a":t,"b":t})
for line in ds:
    print(line)
    break

{'a': <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>, 'b': <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>}


### tensorflow官网实例

In [9]:
# 对list数据源进行数据读取
dataset = tf.data.Dataset.from_tensor_slices([1,2,3])
for element in dataset:
    print(element)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
